### ISSUE TITLE
viewlightslope

### ISSUE THREAD

**Issue by sandsmark** [aap/aoetwols#2]
how did you figure out the patterns to apply/order/etc. for viewlight.inc.c?

there are a couple missing, unless I'm missing something, e. g. a ViewLightSlope_NSE_UP, and I tried to figure out them myself by just guessing and testing a lot, but it's hard to make it look quite right.

**Comment by sandsmark** [comment]
![slope](https://user-images.githubusercontent.com/25765/43063919-b3a492bc-8e5d-11e8-8d6f-ba211a65868c.png)

just to illustrate; those slopes I've highlighted are the ones I've tried to figure out myself. the one to the right looks about right, but the one to the left is kind of broken.

**Comment by aap** [comment]
I reversed them from the exe. It's possible I missed something or made some mistake of course.

**Comment by sandsmark** [comment]
I've been avoiding reversing myself. technically reversing for compatibility is legal, but doing it cleanroom by just looking at your code (and various documentation by others of the file formats) is much more clear-cut.

but thanks anyways, the stuff you've done here has helped immensely.

**Comment by aap** [comment]
I can check if I made some mistake somewhere. The code sure wasn't the prettiest.

**Comment by aap** [comment]
I've just taken a look at this again. Damn, I didn't remember how complex this was. I don't really feel like investigating this right now, but there is a switch at 41F9A8 in age2_x1.exe that corresponds to my switch in ViewDrawTile. Sorry if I wasn't more helpful at the moment.

**Comment by aap** [comment]
Ok, what the hell, I just did it anyway. It's untested, please check if everything looks right. I also found and fixed a small bug (a typo) in the original code.

**Comment by sandsmark** [comment]
thanks a lot!

I owe you a beer (or an alcohol free equivalent in case you prefer that).
